#!/usr/bin/env python3
from __future__ import annotations

import datetime as dt
import html
import pathlib
import re
import subprocess
import urllib.parse

USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0 Safari/537.36"
ACCEPT_LANGUAGE = "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7"

CAFES = [
    {"slug": "soho", "label": "셀러오션"},
    {"slug": "jihosoccer123", "label": "아프니까 사장이다"},
    {"slug": "sellermatchkorea", "label": "위셀랩"},
    {"slug": "no1ssm45123", "label": "스판모넘버원"},
]

KEYWORDS = ["상품명", "리뷰 답글", "상세페이지", "재고 연동"]

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "research" / "snapshots"


def fetch(url: str) -> str:
    result = subprocess.run(
        [
            "curl",
            "-sSL",
            "--compressed",
            "-A",
            USER_AGENT,
            "-H",
            f"Accept-Language: {ACCEPT_LANGUAGE}",
            url,
        ],
        check=True,
        capture_output=True,
    )
    data = result.stdout
    for encoding in ("utf-8", "cp949", "euc-kr"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("utf-8", errors="ignore")


def strip_tags(value: str) -> str:
    text = re.sub(r"<[^>]+>", " ", value)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def cafe_meta(slug: str) -> dict[str, str]:
    url = f"https://cafe.naver.com/{slug}"
    html_text = fetch(url)
    title_match = re.search(r"<title>(.*?)</title>", html_text, re.I | re.S)
    count_match = re.search(r"<em>([0-9,]+)<span class=\"ico_lock2\">비공개</span></em>", html_text)
    return {
        "url": url,
        "title": strip_tags(title_match.group(1)) if title_match else slug,
        "members": count_match.group(1) if count_match else "unknown",
    }


def search_url(slug: str, keyword: str) -> str:
    query = f"site:cafe.naver.com/{slug} 스마트스토어 {keyword}"
    return "https://search.naver.com/search.naver?query=" + urllib.parse.quote(query)


def build_snapshot() -> pathlib.Path:
    now = dt.datetime.now()
    lines = [
        f"# Naver cafe snapshot — {now:%Y-%m-%d %H:%M:%S}",
        "",
        "> Generated by `tools/naver_cafe_snapshot.py`.",
        "> Use the search URLs while logged into Naver for daily manual observation.",
        "",
    ]

    for cafe in CAFES:
        meta = cafe_meta(cafe["slug"])
        lines.extend(
            [
                f"## {cafe['label']}",
                f"- slug: `{cafe['slug']}`",
                f"- url: {meta['url']}",
                f"- title: {meta['title']}",
                f"- member count (public page): {meta['members']}",
                "",
            ]
        )
        for keyword in KEYWORDS:
            lines.extend(
                [
                    f"### 키워드: {keyword}",
                    f"- search: {search_url(cafe['slug'], keyword)}",
                    "",
                ]
            )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUT_DIR / f"naver-cafe-snapshot-{now:%Y%m%d-%H%M%S}.md"
    out_path.write_text("\n".join(lines).strip() + "\n", encoding="utf-8")
    return out_path


if __name__ == "__main__":
    print(build_snapshot())
